#!/usr/bin/env bash
# astryx · postgres backup — the org's WHOLE state (steps, messages, goals, wire
# history, the DB side of memory) lives in ONE docker volume; this is the only thing
# that dumps it. Without it, a `docker volume rm astryx-pgdata`, a corrupted container,
# or disk loss erases the org's entire memory silently.
#
# pg_dump custom-format (-Fc: compressed + selective restore) → backups/astryx-<ts>.dump,
# rotate keep-last-N. The dump is FULL owner-PII: backups/ is personal-tier — gitignored,
# in privacy_gate's SURFACES, NEVER pushed. Offsite copy / at-rest encryption / retention
# tuning are owner-decisions layered ON TOP of this local core.
#
# Run daily by the astryx-backup timer (nucleus/runners.conf); also runnable by hand:
#   ./nucleus/backup.sh [keep-last-N]   (default 14)
set -euo pipefail
cd "$(dirname "$0")/.."
KEEP=${1:-14}

DSN=$(grep '^ASTRYX_DSN=' .env 2>/dev/null | cut -d= -f2-)
[ -n "$DSN" ] || { echo "backup: no ASTRYX_DSN in .env" >&2; exit 1; }

mkdir -p backups
out="backups/astryx-$(date +%Y%m%dT%H%M%S).dump"

# host pg_dump if present, else the container's (mirrors init.sh's psql/docker split)
if command -v pg_dump >/dev/null; then
  pg_dump -Fc "$DSN" > "$out"
else
  docker exec astryx-pg pg_dump -Fc -U astryx astryx > "$out"
fi

# integrity: a pg_dump custom archive begins with the "PGDMP" magic — a truncated or
# error dump (e.g. the DB was down) must NOT count as a backup or silently rotate a good one out.
if [ ! -s "$out" ] || ! head -c 5 "$out" | grep -q 'PGDMP'; then
  echo "backup: dump looks invalid (db down?) — discarding $out" >&2
  rm -f "$out"
  exit 1
fi

# operational state next to the dump — the gitignored dirs that live in NO repo and are NOT
# regenerable: triggers/ (the entire automated immune layer — privacy, metabolism, federation,
# liveness) and memory/ (the compiled wiki). The pg_dump captures the triggers TABLE, but its
# python rows point at THESE files; a restore that brings the rows back without the bodies yields
# an org that looks healthy while silently unguarded — a false-green one level above the
# backup-theater trap restore_verify exists to kill. homes/ is deliberately EXCLUDED: .mcp.json
# is regenerated by spawn.sh and the transcripts are large, so excluding them keeps the artifact
# small enough to stay honest. backups/ is already personal-tier (gitignored + privacy_gate
# SURFACES + the (d) never-commit-type assert), so this adds NO new push surface.
state="${out%.dump}.state.tgz"
state_dirs=""
# agents/ ADDED 2026-08-14, and its absence was the same defect this artifact exists to fix,
# one directory over. The .state.tgz was created because the pg_dump captures the triggers
# TABLE while its rows point at FILES in no repo. Charters are worse off than that: they are
# in no repo WITH A REMOTE (agents/ has zero remotes), in no database (there is no charters
# table), and were in no backup. So every agent's identity — and every reflection each agent
# has written into itself via the scribe, 128 signed commits — existed on exactly one disk.
# 2.5M including .git, which carries the signed authorship history that makes a charter
# attributable at all. Found when offdisk_exposure named the missing remote and I checked
# whether the LOCAL artifact covered it either; it did not.
# NOT an offsite copy: that stays the owner's call, because the working tree holds .env, the
# personal tier and wacli's keys, so exporting it is a credential-and-tier export. This is the
# same local artifact that already holds triggers/ and memory/, at the same tier, gitignored
# and in privacy_gate's SURFACES.
for d in triggers memory agents; do
  if [ -d "$d" ]; then state_dirs="$state_dirs $d"; fi
done
if [ -n "$state_dirs" ]; then
  if ! tar -czf "$state" $state_dirs 2>/dev/null; then
    echo "backup: FAILED to capture operational state ($state_dirs) — the DB dump $out is intact," >&2
    echo "  but restoring it alone would lose the trigger/memory bodies. Fix before trusting." >&2
    rm -f "$state"
    exit 1
  fi
else
  state=""   # fresh org with neither dir — nothing operational to pair (restore check is vacuous)
  echo "backup: note — no triggers/ or memory/ present to capture" >&2
fi

# rotate: keep the newest N of EACH artifact; dump + state share a timestamp so they rotate paired
ls -1t backups/astryx-*.dump      2>/dev/null | tail -n +$((KEEP + 1)) | xargs -r rm -f
ls -1t backups/astryx-*.state.tgz 2>/dev/null | tail -n +$((KEEP + 1)) | xargs -r rm -f

echo "backup: wrote $out ($(du -h "$out" | cut -f1))${state:+ + ${state##*/} ($(du -h "$state" | cut -f1))}; keeping last $KEEP ($(ls -1 backups/astryx-*.dump | wc -l) dumps on disk)"
